# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    config.vm.box      = 'ubuntu/trusty64'
    config.vm.network :forwarded_port, host: 8100, guest: 8000
    config.vm.network :forwarded_port, host: 3000, guest: 3000
        
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end

    config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true
end
